project:
  type: website

website:
  title: "FPFortkamp.com"
  site-url: https://fpfortkamp.com
  description: "Fábio P. Fortkamp's professional website"
  navbar:
    right:
      - about.qmd
      - portfolio.md
      - icon: github
        href: https://github.com/fabiofortkamp
      - icon: twitter
        href: https://x.com/fpfortkamp
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css

editor: visual

